# website title (appears in tab and headers if not overriden by blog title)
name: Featherweight # (leave blank for no fallback/title element)

# website author
author: Featherweight

description: Featherweight is an ultra-lightweight Jekyll theme, aiming to minimise bandwidth usage and deliver a bare-bones experience.

lang: en # replace with ISO 639-1 Language Code for your language (or leave empty to omit the lang setting)

# favicons and icons, use data:, to display an empty icon for low byte cost
icon-32x32: /favicon-32x32.png
icon-64x64: /favicon-16x16.png
manifest: /site.webmanifest
apple-touch-icon: /apple-touch-icon.png
mask-icon:
  href: /safari-pinned-tab.svg
  color: '#5bbad5'
msapplication-TileColor: '#ffffff'
theme-color: '#ffffff'

compression:
  # True to enable, False to disable
  css: True # minimal inline CSS styling, based on https://gist.github.com/JoeyBurzynski/617fb6201335779f8424ad9528b72c41.
  footer: True  # add personal links as footer to blog posts
  home-link: True  # add a home link to top left corner of blog posts, navigates to website root.
  load-time: True # show-off your page size + load speed top of the page (uses JS).
  reading-time: True # add reading time estimate to your blog posts.
  seo: True # apply SEO (add metadata, etc., support for Twitter and Facebook linking)
  social-urls: True # include URL list on the homepage.
  resume: True # include resume section on the homepage.
  blogs: True # include blog posts listed in /_posts on the homepage.
  page-size: True # report page size (count of bytes in page source - approximate as bytes used in report not included)
  favicon: True # include favicon info in page header

home-link-text: Return Home # text used for home link displayed on posts when home-link: True. Customise e.g.: "{{ site.name }}", "Home", "Back", etc.

# domain URL (use https to enforce SSL)
# if website root is at subdirectory of domain URL (e.g.: "https://cutwell.github.io/mywebsite"), then write that URL here
url: https://cutwell.github.io/featherweight

google-site-verification: # add your verification token here (https://developers.google.com/site-verification/)


##### JEKYLL SETTINGS #####
permalink: /:title/

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-zopfli # github auto-compresses to .gz, but Zopfli offers greater compression + saves time by pre-compressing instead of doing it on-the-fly
  - jekyll-brotli # Google compression that outperforms Zopfli, and has good support (although less than .gz, hence using both to provice fallback)
  - jekyll-anti-image-reflow # prevent page reflow while lazy-loading images

include: ['_pages']

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# use https://github.com/penibelst/jekyll-compress-html for extra bandwidth compression
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head]
  profile: false
  blanklines: false
  ignore:
    envs: []

# RSS feed settings
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
